Repository pharmacome/conib, pull requests merged in 2019-05, with the labels that each got.

#135 Recurate balaji2018
  hbp_knowledge/tau/balaji2018.bel
Labels: Recuration

#136 recuration boland2018
  hbp_knowledge/tau/boland2018.bel
Labels: Recuration

#139 recuration chesser2013
  hbp_knowledge/tau/chesser2013.bel
Labels: Recuration

#140 recuration defelice2008
  hbp_knowledge/tau/defelice2008.bel
Labels: Recuration

#141 recuration despres2017
  hbp_knowledge/tau/despres2017.bel
Labels: Recuration

#142 recuration fatouros2012
  hbp_knowledge/tau/fatouros2012.bel
Labels: Recuration

#143 recuration frandemiche2014
  hbp_knowledge/tau/frandemiche2014.bel
Labels: Recuration

#158 Recurate lee2013
  hbp_knowledge/tau/lee2013.bel
Labels: Recuration

#159 Recurate martini-stoica2018
  hbp_knowledge/tau/martini‐stoica2018.bel
Labels: Recuration

#161 Recurate mirbaha2015
  hbp_knowledge/tau/mirbaha2015.bel
Labels: Recuration

#162 Recurate mirbaha2018
  hbp_knowledge/tau/mirbaha2018.bel
Labels: Recuration

#163 Recurate nobuhara2017
  hbp_knowledge/tau/nobuhara2017.bel
Labels: Recuration

#182 Recurate pickhardt2018
  hbp_knowledge/tau/pickhardt2018.bel
Labels: Recuration

#181 Recurate park2012
  hbp_knowledge/tau/park2012.bel
Labels: Recuration

#184 Recurate shelton2017
  hbp_knowledge/tau/shelton2017.bel
Labels: Recuration

#185 Recurate takeda2015
  hbp_knowledge/tau/takeda2015.bel
Labels: Recuration

#183 Recurate schweig2017
  hbp_knowledge/tau/schweig2017.bel
Labels: Recuration

#137 Recurate yamada2017
  hbp_knowledge/tau/yamada2017.bel
Labels: Recuration

#154 Recurate tiernan2016
  hbp_knowledge/tau/tiernan2016.bel
Labels: Recuration

#165 add recuration tarasoffconway2015
  hbp_knowledge/tau/tarasoffconway2015.bel
Labels: Recuration

#166 add recuration simic2016
  hbp_knowledge/tau/simic2016.bel
Labels: Recuration

#169 add recuration saidi2015
  hbp_knowledge/tau/saidi2015.bel
Labels: Recuration

#187 Recurate pir2017
  hbp_knowledge/tau/pir2017.bel
Labels: Recuration

#188 Recurate paris2014
  hbp_knowledge/tau/paris2014.bel
Labels: Recuration

#192 Recurate joseph2017
  hbp_knowledge/tau/joseph2017.bel
Labels: Recuration

#190 Recurate kaniyappan2017
  hbp_knowledge/tau/kaniyappan2017.bel
Labels: Recuration

#152 Recurate wang2017
  hbp_knowledge/pp2a/wang2017.bel
Labels: Recuration, Topic: PP2A

#156 Recurate torrent2012
  hbp_knowledge/pp2a/torrent2012.bel
Labels: Recuration, Topic: PP2A

#177 Recurate ferreira-vieira2016
  hbp_knowledge/receptors/ferreira-vieira2016.bel
Labels: Recuration

#172 Recurate sontag2014
  hbp_knowledge/pp2a/sontag2014.bel
Labels: Recuration, Topic: PP2A

#202 Recurate nedelsky2008
  hbp_knowledge/proteostasis/nedelsky2008.bel
Labels: Recuration, Topic:Proteostasis

#207 Recurate ciechanover2013
  hbp_knowledge/proteostasis/ciechanover2013.bel
Labels: Recuration, Topic:Proteostasis

#160 Recurate terwel2002
  hbp_knowledge/pp2a/terwel2002.bel
Labels: Recuration, Topic: PP2A

#227 Curate maniati2019
  hbp_knowledge/maniati2019.bel
Labels: Curation

#226 Curate ryan2019
  hbp_knowledge/ryan2019.bel
Labels: Curation, Topic: Tau modification

#225 Curate yamada2018
  hbp_knowledge/yamada2018.bel
Labels: Curation, Topic: Tau transport

#224 Curate ryskalin2018
  hbp_knowledge/ryskalin2018.bel
Labels: Curation

#223 Recurate-miwa2011-trusha19
  hbp_knowledge/receptors/miwa2011.bel
Labels: Recuration

#144 Recurate morsy2018.bel
  hbp_knowledge/app/morsy2018.bel
Labels: Recuration

#230 Recurate tau_modifications_nestor
  hbp_knowledge/tau/nestor/tau_modifications.bel
Labels: Recuration

#147 Recurate lewis1996
  hbp_knowledge/antalarmin/lewis1996.bel
Labels: Recuration, Topic: Anatabine

#149 Recurate alderman2018
  hbp_knowledge/antalarmin/alderman2018.bel
Labels: Recuration

#206 Recurate dani2007
  hbp_knowledge/receptors/dani2007.bel
Labels: Recuration

#220 Recurate lombardo2015
  hbp_knowledge/receptors/lombardo2015.bel
Labels: Recuration

#218 Recurate taly2009
  hbp_knowledge/receptors/taly2009.bel
Labels: Recuration

#215 Recurate nordberg2001
  hbp_knowledge/receptors/nordberg2001.bel
Labels: Recuration

#211 Recurate post-munson2017
  hbp_knowledge/receptors/post-munson2017.bel
Labels: Recuration

#210 Recurate sadigh-eteghad2015
  hbp_knowledge/receptors/sadigh-eteghad2015.bel
Labels: Recuration

#209 Recurate matta2017
  hbp_knowledge/receptors/matta2017.bel
Labels: Recuration

#208 Recurate mandrekar2011
  hbp_knowledge/receptors/mandrekar2011.bel
Labels: Recuration

#197 Recurate ren2007
  hbp_knowledge/receptors/ren2007.bel
Labels: Recuration

#194 Recurate lorenz2014
  hbp_knowledge/receptors/lorenz2014.bel
Labels: Recuration

#193 Recurate lombardo2015b
  hbp_knowledge/receptors/lombardo2015b.bel
Labels: Recuration

#186 Recurate yu2014
  hbp_knowledge/proteostasis/yu2014.bel
Labels: Recuration, Topic:Proteostasis

#179 Recurate francis2016
  hbp_knowledge/receptors/francis2016.bel
Labels: Recuration

#168 Recurate choi2012
  hbp_knowledge/receptors/choi2014.bel
Labels: Recuration

#155 Recurate albuquerque2009
  hbp_knowledge/receptors/albuquerque2009.bel
Labels: Recuration

#157 Recurate kanaan2011
  hbp_knowledge/tau/kanaan2011.bel
Labels: Recuration

#234 Curate monahan2016
  hbp_knowledge/tardbp/monahan2016.bel
Labels: Curation, Topic: TARDBP

#235 Curate xia2016
  hbp_knowledge/tardbp/xia2016.bel
Labels: Curation, Topic: TARDBP
