Repository pharmacome/conib, pull requests merged in 2019-11, with the labels that each got.

#385 Recurate iaconelli2015
  hbp_knowledge/hdac6/iaconelli2015.bel
Labels: Task: Recuration

#387 Recurate deydewalle2012
  hbp_knowledge/hdac6/deydewalle2012.bel
Labels: Task: Recuration

#388 Recurate simoes2013
  hbp_knowledge/hdac6/simoes2013.bel
Labels: Task: Recuration

#291 Curate ayala2008
  hbp_knowledge/tardbp/ayala2008.bel
Labels: Task: Curation, Topic: TARDBP

#389 Curate martini stocia2016
  hbp_knowledge/tfeb/README.rst
  hbp_knowledge/tfeb/martini-stocia2016.bel
Labels: Task: Curation, Topic: TFEB

#369 Recurate boxberger209
  hbp_knowledge/ms/boxberger209.bel
Labels: Task: Recuration

#390 Recurate kontsekova2014
  hbp_knowledge/immunotherapy/kontsekova2014.bel
Labels: Task: Recuration, Topic: Immuntherapy

#348 Curate kontsekova2014_2
  hbp_knowledge/immunotherapy/kontsekova2014_2.bel
Labels: Task: Curation, Topic: Immuntherapy

#372 Curate forest2019
  hbp_knowledge/receptors/forest2019.bel
Labels: Task: Curation, Topic: Receptor

#384 Recurate carlomagno2017
  hbp_knowledge/hdac6/carlomagno2017.bel
Labels: Task: Recuration

#381 Recurate jadhav2013
  hbp_knowledge/immunotherapy/jadhav2013.bel
Labels: Task: Recuration

#383 Recurate cohen2011
  hbp_knowledge/hdac6/cohen2011.bel
Labels: Task: Recuration

#370 Recurate chang2013
  hbp_knowledge/tardbp/chang2013.bel
Labels: Task: Recuration

#394 Recurate kontsekova2014_2
  hbp_knowledge/immunotherapy/kontsekova2014_2.bel
Labels: Task: Recuration

#386 Recurate park2018
  hbp_knowledge/hdac6/park2018.bel
Labels: Task: Recuration

#393 Recurate ayala2008
  hbp_knowledge/tardbp/ayala2008.bel
Labels: Task: Recuration

#392 Recurate shefa2019
  hbp_knowledge/oxidative-stress/shefa2019.bel
Labels: Task: Recuration

#391 Recurate forest2019
  hbp_knowledge/receptors/forest2019.bel
Labels: Task: Recuration, Topic: Receptor

#397 Curate kalkman2016
  hbp_knowledge/receptors/kalkman2016.bel
Labels: Task: Curation, Topic: Receptor

#399 Curate bao2016
  hbp_knowledge/tfeb/bao2016.bel
Labels: Task: Curation, Topic: TFEB

#398 Curate corradi2016
  hbp_knowledge/receptors/corradi2016.bel
Labels: Task: Curation, Topic: Receptor

#395 Curate martini stocia2018
  hbp_knowledge/tfeb/martini-stoica2018.bel
Labels: Task: Curation, Topic: TFEB

#401 Recurate tau_biochemistry
  hbp_knowledge/tau/taubase/tau_biochemistry.bel
Labels: Task: Recuration, Topic: Tau modification

#403 Recurate taubase tau interacting partners
  hbp_knowledge/tau/taubase/tau_interaction_partners.bel
Labels: Task: Recuration, Topic: Tau modification

#406 Recurate bao2016
  hbp_knowledge/tfeb/bao2016.bel
Labels: Task: Recuration

#407 Curate kabbani2018
  hbp_knowledge/receptors/kabbani2018.bel
Labels: Task: Curation, Topic: Receptor

#405 Recurate martini-stoica2018
  hbp_knowledge/tfeb/martini-stoica2018.bel
Labels: Task: Recuration

#400 Recurate kalkman2016
  hbp_knowledge/receptors/kalkman2016.bel
Labels: Task: Recuration, Topic: Receptor

#402 Recurate corradi2016
  hbp_knowledge/receptors/corradi2016.bel
Labels: Task: Recuration, Topic: Receptor

#396 Recurate martini-stocia2016
  hbp_knowledge/tfeb/martini-stocia2016.bel
Labels: Task: Recuration

#404 Curate sardiello2016
  hbp_knowledge/tfeb/sardiello2016.bel
Labels: Task: Curation, Topic: TFEB

#382 Recurate prasad2019
  hbp_knowledge/tardbp/prasad2019.bel
Labels: Task: Recuration

#380 Recurate correale2017
  hbp_knowledge/ms/correale2017.bel
Labels: Task: Recuration
