Repository pharmacome/conib, pull requests merged in 2019-02, with the labels that each got.

#28 Curate dani2015
  bel/dani2015.bel
Labels: Curation

#90 Lingling lorenz2014
  hbp_knowledge/lorenz2014.bel
Labels: Curation

#87 curation miyata2011
  hbp_knowledge/miyata2011.bel
Labels: Curation

#86 curation taipale2014
  hbp_knowledge/taipale2014.bel
Labels: Curation

#85 add curation lee2013
  hbp_knowledge/lee2013.bel
Labels: Curation

#84 add curation shelton2017
  hbp_knowledge/shelton2017.bel
Labels: Curation

#83 add curation morimoto2015
  hbp_knowledge/morimoto2015.bel
Labels: Curation

#82 add curation brehme2014
  hbp_knowledge/brehme2014.bel
Labels: Curation

#73 Curate king2015
  hbp_knowledge/king2015.bel
Labels: Curation

#71 Create heneka2017.bel
  hbp_knowledge/heneka2017.bel
Labels: Curation

#70 Create gant2018.bel
  hbp_knowledge/gant2018.bel
Labels: Curation

#66 Create despres2017.bel
  hbp_knowledge/despres2017.bel
Labels: Curation

#27 Curate alderman2018
  hbp_knowledge/alderman2018.bel
Labels: Curation

#31 Curate defelice2008
  hbp_knowledge/defelice2008.bel
Labels: Curation

#32 Curate dani2007
  hbp_knowledge/dani2007.bel
Labels: Curation

#34 Create baumann1993.bel
  hbp_knowledge/baumann1993.bel
Labels: Curation

#35 Create bengoa2017.bel
  hbp_knowledge/bengoa2017.bel
Labels: Curation

#36 Create biswas2016.bel
  hbp_knowledge/biswas2016.bel
Labels: Curation

#47 Create simic2016.bel
  hbp_knowledge/simic2016.bel
Labels: Curation

#57 Create maccecchini2012.bel
  hbp_knowledge/maccecchini2012.bel
Labels: Curation

#62 Create caballero2018.bel
  hbp_knowledge/caballero2018.bel
Labels: Curation

#80 Create zoli2018.bel
  hbp_knowledge/zoli2018.bel
Labels: Curation

#81 Add djouma2016.bel
  hbp_knowledge/djouma2006.bel
Labels: Curation

#105 add curation pickhardt2018
  hbp_knowledge/pickhardt2018.bel
Labels: Curation, Mandelkow

#102 Curate balaji2018
  hbp_knowledge/balaji2018.bel
Labels: Curation, Mandelkow

#94 curation chung2018
  hbp_knowledge/chung2018.bel
Labels: Curation, Topic:Proteostasis

#95 curation nedelsky2008
  hbp_knowledge/nedelsky2008.bel
Labels: Curation, Topic:Proteostasis

#96 curation ihara2012
  hbp_knowledge/ihara2012.bel
Labels: Curation, Topic:Proteostasis

#101 add curation kim2013
  hbp_knowledge/kim2013.bel
Labels: Curation, Topic:Proteostasis

#97 curation kaniyappan2017
  hbp_knowledge/kaniyappan2017.bel
Labels: Curation, Mandelkow

#99 add curation yu2014
  hbp_knowledge/yu2014.bel
Labels: Curation, Topic:Proteostasis

#104 curation pir2017
  hbp_knowledge/pir2017.bel
Labels: Curation, Mandelkow

#106 curation wang2015
  hbp_knowledge/wang2015.bel
Labels: Curation, Mandelkow
