Repository pharmacome/conib, pull requests merged in 2019-10, with the labels that each got.

#350 Recurate maccecchini2012
  hbp_knowledge/app/maccecchini2012.bel
Labels: Task: Recuration

#356 Recurate yamada2018
  hbp_knowledge/tau/yamada2018.bel
Labels: Task: Recuration, Topic: Tau transport

#355 Recurate ryan2019
  hbp_knowledge/tau/ryan2019.bel
Labels: Task: Recuration, Topic: Tau modification

#352 Recurate gant2018
  hbp_knowledge/misc/gant2018.bel
Labels: Task: Recuration

#351 Recurate maniati2019
  hbp_knowledge/misc/maniati2019.bel
Labels: Task: Recuration

#340 Recurate min2018
  hbp_knowledge/hdac6/min2018.bel
Labels: Task: Recuration

#342 Recurate sarantos2012
  hbp_knowledge/huntington/sarantos2012.bel
Labels: Task: Recuration, Topic: Huntington

#343 Recurate brownlee2016
  hbp_knowledge/ms/brownlee2016.bel
Labels: Task: Recuration, Topic: MS

#336 Recurate iaconelli2019
  hbp_knowledge/hdac6/iaconelli2019.bel
Labels: Task: Recuration

#347 Curate ontaneda2016
  hbp_knowledge/ms/ontaneda2016.bel
Labels: Task: Curation, Topic: MS

#346 Curate fan2018
  hbp_knowledge/hdac6/fan2018.bel
Labels: Task: Curation, Topic: HDAC6

#359 Curate jadhav2013
  hbp_knowledge/immunotherapy/jadhav2013.bel
Labels: Task: Curation, Topic: Immuntherapy

#357 Curate echeverria2012
  hbp_knowledge/receptors/echeverria2012.bel
Labels: Task: Curation

#354 Recurate miyata2011
  hbp_knowledge/tau/miyata2011.bel
Labels: Task: Recuration, Topic: Tau modification

#345 Curate cook2014
  hbp_knowledge/hdac6/cook2014.bel
Labels: Task: Curation, Topic: HDAC6

#335 Recurate wang2019
  hbp_knowledge/ms/wang2019.bel
Labels: Task: Recuration, Topic: MS

#341 Curate comi2016
  hbp_knowledge/ms/comi2016.bel
Labels: Task: Curation, Topic: MS

#330 Recurate guo2019
  hbp_knowledge/er-stress/guo2019.bel
Labels: Task: Recuration

#304 Recurate loi2018
  hbp_knowledge/huntington/loi2018.bel
Labels: Task: Recuration

#287 Curate boxberger2019
  hbp_knowledge/ms/boxberger209.bel
Labels: Task: Curation, Topic: MS

#248 Curate prasad2019
  hbp_knowledge/tardbp/prasad2019.bel
Labels: Task: Curation, Topic: TARDBP

#213 Curate shefa2019
  hbp_knowledge/shefa2019.bel
Labels: Task: Curation

#337 Curate deming2019
  hbp_knowledge/phagocytosis/deming2019.bel
Labels: Task: Curation, Topic: Phagocytosis

#282 Curate correale2017
  hbp_knowledge/ms/correale2017.bel
Labels: Task: Curation, Topic: MS

#360 Curate paul2000
  hbp_knowledge/inflammasome/paul2000.bel
Labels: Task: Curation

#288 Curate cappa2017
  hbp_knowledge/ms/cappa2017.bel
Labels: Task: Curation, Topic: MS

#146 Recurate wang2015
  hbp_knowledge/tau/wang2015.bel
Labels: Task: Recuration

#358 Curate majdi2019
  hbp_knowledge/receptors/majdi2019.bel
Labels: Task: Curation

#338 Curate kontsekova2014
  hbp_knowledge/immunotherapy/README.rst
  hbp_knowledge/immunotherapy/kontsekova2014.bel
Labels: Task: Curation, Topic: Immuntherapy

#362 Recurate comi2016
  hbp_knowledge/ms/comi2016.bel
Labels: Task: Recuration, Topic: MS

#361 Recurate echeverria2012
  hbp_knowledge/receptors/echeverria2012.bel
Labels: Topic: Receptor

#363 Recurate ontaneda2016
  hbp_knowledge/ms/ontaneda2016.bel
Labels: Task: Recuration, Topic: MS

#377 Recurate majdi2019
  hbp_knowledge/receptors/majdi2019.bel
Labels: Task: Recuration, Topic: Receptor

#379 Curate cohen2011
  hbp_knowledge/hdac6/cohen2011.bel
Labels: Task: Curation, Topic: HDAC6

#375 Recurate cappa2017
  hbp_knowledge/ms/cappa2017.bel
Labels: Task: Recuration

#374 Recurate Bruch2017
  hbp_knowledge/er-stress/bruch2017.bel
Labels: Task: Recuration

#373 Recurate kontsekova2014
  hbp_knowledge/immunotherapy/kontsekova2014.bel
Labels: Task: Recuration

#378 Curate deydewalle2012
  hbp_knowledge/hdac6/deydewalle2012.bel
Labels: Task: Curation, Topic: HDAC6

#376 Curate park2018
  hbp_knowledge/hdac6/park2018.bel
Labels: Task: Curation, Topic: HDAC6

#334 Curate simoes2013
  hbp_knowledge/hdac6/simoes2013.bel
Labels: Task: Curation, Topic: HDAC6

#371 Curate iaconelli2015
  hbp_knowledge/hdac6/iaconelli2015.bel
  hbp_knowledge/tau/taubase/tau_modifications.bel
Labels: Task: Curation, Topic: HDAC6

#365 Recurate deming2019
  hbp_knowledge/phagocytosis/deming2019.bel
Labels: Task: Recuration

#367 Recurate cook2014
  hbp_knowledge/hdac6/cook2014.bel
Labels: Task: Recuration

#366 Recurate fan2018
  hbp_knowledge/hdac6/fan2018.bel
Labels: Task: Recuration

#368 Curate carlomagno2017
  hbp_knowledge/hdac6/carlomagno2017.bel
  hbp_knowledge/tau/taubase/tau_modifications.bel
Labels: Task: Curation, Topic: HDAC6

#364 Recurate paul2000
  hbp_knowledge/inflammasome/paul2000.bel
Labels: Task: Recuration

#305 Recurate pandey2018
  hbp_knowledge/huntington/pandey2018.bel
Labels: Task: Recuration, Topic: Huntington

#200 Recurate dennissen2016
  hbp_knowledge/tau/dennissen2016.bel
Labels: Task: Recuration

#353 Recurate bulic2012
  hbp_knowledge/tau/bulic2012.bel
Labels: Task: Recuration, Topic: Tau modification
